### ISSUE TITLE
Fix: WantedJd 엔티티 scraping_date 컬럼 타입 변경

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/f1-JDON-Backend#420]
> TODO

WantedJd 엔티티 및 wantedjd 테이블 컬럼타입 변경 필요

> Description

wantedjd 테이블의 scraping_date 컬럼으로 정렬 시 정렬되지 않는 문제를 발견했습니다.
원인을 찾아보니 wantedjd 테이블 scraping_date 컬럼이 DATE 타입이 아닌 TEXT 타입으로 잘못 생성되어 있었고, 이를 해결하고자 컬럼 타입 변경이 필요합니다.

현재 생각나는 방법으로는
1. DATE 타입의 TEMP 컬럼을 신규 생성
2. 기존 scraping_date 컬럼 데이터를 DATE 타입으로 형변환하여 TEMP 컬럼에 복사
3. 기존 scraping_date 컬럼을 삭제
4. TEMP 컬럼명을 scraping_date으로 변경

위 순서로 해결해야할 것 같은데 더 자세한 내용은 찾아보도록 하겠습니다.

**Comment by anso33** [comment]
https://medium.com/@chuck.m.park/introduction-7233374e0ba3
