### ISSUE TITLE
Fix: 인프런 크롤링 스케줄러

### ISSUE THREAD

**Issue by aacara** [Kernel360/f1-JDON-Backend#513]
> TODO
- 스케줄러에 등록된 잡 이름 변경하겠습니다.

> Description

**Comment by yoonseon12** [comment]
현지님 안녕하세요.
스프링 멘토님께 스프링 빈 이름을 한글로 등록하는 경우가 있냐고 질문드렸었는데.. 실무에서는 스프링 빈, 변수명 등을 한글로 명명하는 일은 절대 안쓴다는 답변을 받았습니다.. 

제가 스프링 배치 스케줄러를 구현할 때 참고했던 리포지토리에 Job 및 step의 빈 이름을 한글로 명시하게 구현해두었었는데, 제 기준에 신박하고 더 명시적이라는 느낌을 받았었고 그래서 저도 Job 및 step의 빈 이름을 한글로 구현했었는데 멘토링 답변을 듣고 다시 빈 이름을 다시 영문으로 변경했습니다ㅎㅎ...

따라서 잡 이름을 한글로 바꾸시지 않으셔도 됩니다 !

저는 조금 더 이 Job이 어떤 일을 하는지 명시하는 부분은 주석으로 대신 달았어요~ 아래래와 같이 수정했답니다 !
![image](https://github.com/Kernel360/f1-JDON-Backend/assets/59242594/bb682816-e955-4571-a61d-c6df4056d480)
